spring.application.name=CatanBackend
spring.datasource.url=jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.bhkfsjidkjbafxyhcsur
spring.datasource.password=oicar123123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.hibernate.ddl-auto=update


# Connection Pooling (Optional - Improves performance)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000


spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

jwt.secret = "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"