ALTER TABLE tile_edges
    DROP CONSTRAINT fk7kua6p4sd1ltogjb55hmg0817;

ALTER TABLE tiles
    DROP CONSTRAINT fk_tiles_on_resource;

ALTER TABLE structures
    DROP CONSTRAINT fka1bm1c9pmc85y8yhgynu6fkts;

ALTER TABLE tile_corners
    DROP CONSTRAINT fkayx68y3lis2mkf1myh047w4y;

ALTER TABLE roads
    DROP CONSTRAINT fkd60ldk8885nik5im45h88todu;

CREATE TABLE tile_types
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    resource_id BIGINT,
    CONSTRAINT pk_tile_types PRIMARY KEY (id)
);

ALTER TABLE sessions
    ADD current_player_id BIGINT;

ALTER TABLE sessions
    ADD map_generated BOOLEAN;

ALTER TABLE sessions
    ADD victory_points_condition INTEGER;

ALTER TABLE dev_cards
    ADD session_id BIGINT;

ALTER TABLE tiles
    ADD tile_type_id BIGINT;

ALTER TABLE session_players
    ADD turn_order INTEGER;

ALTER TABLE player_profiles
    ADD CONSTRAINT uc_player_profiles_user UNIQUE (user_id);

ALTER TABLE resources
    ADD CONSTRAINT uc_resources_name UNIQUE (name);

ALTER TABLE structure_types
    ADD CONSTRAINT uc_structure_types_name UNIQUE (name);

ALTER TABLE tile_types
    ADD CONSTRAINT uc_tile_types_name UNIQUE (name);

ALTER TABLE tile_types
    ADD CONSTRAINT uc_tile_types_resource UNIQUE (resource_id);

ALTER TABLE dev_cards
    ADD CONSTRAINT FK_DEV_CARDS_ON_SESSION FOREIGN KEY (session_id) REFERENCES sessions (id);

ALTER TABLE sessions
    ADD CONSTRAINT FK_SESSIONS_ON_CURRENT_PLAYER FOREIGN KEY (current_player_id) REFERENCES session_players (id);

ALTER TABLE tiles
    ADD CONSTRAINT FK_TILES_ON_TILE_TYPE FOREIGN KEY (tile_type_id) REFERENCES tile_types (id);

ALTER TABLE tile_types
    ADD CONSTRAINT FK_TILE_TYPES_ON_RESOURCE FOREIGN KEY (resource_id) REFERENCES resources (id);

DROP TABLE cities CASCADE;

ALTER TABLE player_profiles
    DROP COLUMN brick;

ALTER TABLE player_profiles
    DROP COLUMN bricks;

ALTER TABLE player_profiles
    DROP COLUMN crystal;

ALTER TABLE player_profiles
    DROP COLUMN gold;

ALTER TABLE player_profiles
    DROP COLUMN grain;

ALTER TABLE player_profiles
    DROP COLUMN lumber;

ALTER TABLE player_profiles
    DROP COLUMN obsidian;

ALTER TABLE player_profiles
    DROP COLUMN ore;

ALTER TABLE player_profiles
    DROP COLUMN rice;

ALTER TABLE player_profiles
    DROP COLUMN sheep;

ALTER TABLE player_profiles
    DROP COLUMN silver;

ALTER TABLE player_profiles
    DROP COLUMN wood;

ALTER TABLE player_profiles
    DROP COLUMN wool;

ALTER TABLE session_players
    DROP COLUMN bricks;

ALTER TABLE session_players
    DROP COLUMN grain;

ALTER TABLE session_players
    DROP COLUMN lumber;

ALTER TABLE session_players
    DROP COLUMN obsidian;

ALTER TABLE session_players
    DROP COLUMN wool;

ALTER TABLE structures
    DROP COLUMN corner_index;

ALTER TABLE structures
    DROP COLUMN owner;

ALTER TABLE structures
    DROP COLUMN tile_id;

ALTER TABLE structures
    DROP COLUMN type;

ALTER TABLE tile_corners
    DROP COLUMN corners;

ALTER TABLE tile_corners
    DROP COLUMN tile_id;

ALTER TABLE roads
    DROP COLUMN edge_index;

ALTER TABLE roads
    DROP COLUMN owner;

ALTER TABLE roads
    DROP COLUMN tile_id;

ALTER TABLE tile_edges
    DROP COLUMN edges;

ALTER TABLE tile_edges
    DROP COLUMN tile_id;

ALTER TABLE tiles
    DROP COLUMN resource_id;

ALTER TABLE resources
    ALTER COLUMN name SET NOT NULL;

ALTER TABLE structure_types
    ALTER COLUMN name SET NOT NULL;

ALTER TABLE tile_edges
    ALTER COLUMN road_id DROP NOT NULL;